import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HorizontalScroll from "./components/HorizontalScroll";
import TopImages from "./components/TopImages";
import ParallaxText from "./components/ParallaxText"
import ImageDisappear from "./components/ImageDisappear";
import Footer from "./components/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Lama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ImageDisappear />

      <TopImages />

      <section>
        <ParallaxText baseVelocity={-1} color="#E5D1FA">Lamoseshka Farfosheka is the Cutest Patotes to ever exist</ParallaxText>
        <ParallaxText baseVelocity={1} color="#E5D1FA">You are my favorite thing in life - Loving You Forever & Always</ParallaxText>
      </section>

      <HorizontalScroll />

      <Footer />
      
    </>
  )
}
